Template refactor terraform (#193)
* major template refactoring -> terraform module is the sun

* major template refactoring -> terraform module is the sun

* major template refactoring -> terraform module is the sun

* terraform module relative path.

* upgrade linter

* Create temporary directory

* Do not validate env

* Linter changes

* Linter changes

* Linter changes

* Linter changes

* Linter changes

* Linter changes

* Linter changes

* fix variable override

* bump nomad and update changelog

* added docker-build + cleanup (#194)

* added docker-build + cleanup

* Update template/docker/README.md

Co-authored-by: Fredrik Hoem Grelland <40291976+fredrikhgrelland@users.noreply.github.com>

* removed build-docker

Co-authored-by: Per Daniel Thorsrud <perdaniel.thorsrud@skatteetaten>
Co-authored-by: Fredrik Hoem Grelland <40291976+fredrikhgrelland@users.noreply.github.com>

* testing the tests

* testing the tests

* linter fixes

* fix ansible startup

* fix ansible startup

* fix linting

* fix linting

* various fixes

* lint fix

* reduce conditionals

* reduce conditionals

* remove clutter

* fix booleans

* fix wording

* you must remove box before testing

* fix conditional for undefined local_test

* Update template/test_example/dev/ansible/00_test_namespace_seperation.yml

Co-authored-by: Per Daniel Thorsrud <51820995+pdmthorsrud@users.noreply.github.com>

* Fix documentation

* remove file

* Update ansible/bootstrap.yml

Co-authored-by: Per Daniel Thorsrud <51820995+pdmthorsrud@users.noreply.github.com>

Co-authored-by: Per Daniel Thorsrud <51820995+pdmthorsrud@users.noreply.github.com>
Co-authored-by: Per Daniel Thorsrud <perdaniel.thorsrud@skatteetaten>

diff --git a/template/Makefile b/template/Makefile
--- a/template/Makefile
+++ b/template/Makefile
@@ -1,4 +1,4 @@
-include .env
+include dev/.env
 export
 export PATH := $(shell pwd)/tmp:$(PATH)
 
@@ -7,11 +7,24 @@ export PATH := $(shell pwd)/tmp:$(PATH)
 
 #### Development ####
 # start commands
-up: clean update-box
-	SSL_CERT_FILE=${SSL_CERT_FILE} CURL_CA_BUNDLE=${CURL_CA_BUNDLE} vagrant up --provision
+dev: update-box
+	SSL_CERT_FILE=${SSL_CERT_FILE} CURL_CA_BUNDLE=${CURL_CA_BUNDLE} ANSIBLE_ARGS='--skip-tags "test"' vagrant up --provision
 
-update-box:
-	@SSL_CERT_FILE=${SSL_CERT_FILE} CURL_CA_BUNDLE=${CURL_CA_BUNDLE} vagrant box update || (echo '\n\nIf you get an SSL error you might be behind a transparent proxy. \nMore info https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/README.md#if-you-are-behind-a-transparent-proxy\n\n' && exit 2)
+up: update-box
+ifdef CI # CI is set in Github Actions
+	SSL_CERT_FILE=${SSL_CERT_FILE} CURL_CA_BUNDLE=${CURL_CA_BUNDLE} vagrant up --provision
+else
+	SSL_CERT_FILE=${SSL_CERT_FILE} CURL_CA_BUNDLE=${CURL_CA_BUNDLE} ANSIBLE_ARGS='--extra-vars "local_test=true"' vagrant up --provision
+endif
+
+test: clean up
+
+example:
+ifdef CI # CI is set in Github Actions
+	cd test_example; SSL_CERT_FILE=${SSL_CERT_FILE} CURL_CA_BUNDLE=${CURL_CA_BUNDLE} vagrant up --provision
+else
+	cd test_example; SSL_CERT_FILE=${SSL_CERT_FILE} CURL_CA_BUNDLE=${CURL_CA_BUNDLE} ANSIBLE_ARGS='--extra-vars "local_test=true"' vagrant up --provision
+endif
 
 # clean commands
 destroy-box:
@@ -22,16 +35,7 @@ remove-tmp:
 
 clean: destroy-box remove-tmp
 
-test:
-ifeq (,$(wildcard ansible/playbook.yml))
-	echo ERROR: There is no playbook.yml available in ansible/ && exit 2
-else
-	make clean
-	make up
-endif
+# helper commands
+update-box:
+	@SSL_CERT_FILE=${SSL_CERT_FILE} CURL_CA_BUNDLE=${CURL_CA_BUNDLE} vagrant box update || (echo '\n\nIf you get an SSL error you might be behind a transparent proxy. \nMore info https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/README.md#if-you-are-behind-a-transparent-proxy\n\n' && exit 2)
 
-example:
-	cd example; SSL_CERT_FILE=${SSL_CERT_FILE} CURL_CA_BUNDLE=${CURL_CA_BUNDLE} vagrant up --provision
-
-build:
-	echo "building docker image"
