added docker-build + cleanup

diff --git a/template/Makefile b/template/Makefile
--- a/template/Makefile
+++ b/template/Makefile
@@ -7,11 +7,16 @@ export PATH := $(shell pwd)/tmp:$(PATH)
 
 #### Development ####
 # start commands
-up: clean update-box
+up: update-box
 	SSL_CERT_FILE=${SSL_CERT_FILE} CURL_CA_BUNDLE=${CURL_CA_BUNDLE} vagrant up --provision
 
-update-box:
-	@SSL_CERT_FILE=${SSL_CERT_FILE} CURL_CA_BUNDLE=${CURL_CA_BUNDLE} vagrant box update || (echo '\n\nIf you get an SSL error you might be behind a transparent proxy. \nMore info https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/README.md#if-you-are-behind-a-transparent-proxy\n\n' && exit 2)
+test: clean up
+
+example:
+	cd test_example; SSL_CERT_FILE=${SSL_CERT_FILE} CURL_CA_BUNDLE=${CURL_CA_BUNDLE} vagrant up --provision
+
+build-docker: check-dockerfile
+	cd docker; docker build -t $(IMAGE_NAME) .
 
 # clean commands
 destroy-box:
@@ -22,13 +27,13 @@ remove-tmp:
 
 clean: destroy-box remove-tmp
 
-test:
-ifeq (,$(wildcard ansible/playbook.yml))
-	echo ERROR: There is no playbook.yml available in ansible/ && exit 2
-else
-	make clean
-	make up
+# helper commands
+
+check-dockerfile:
+ifeq (,$(wildcard docker/Dockerfile))
+	echo ERROR: There is no Dockerfile available in docker/ && exit 2
 endif
 
-example:
-	cd test_example; SSL_CERT_FILE=${SSL_CERT_FILE} CURL_CA_BUNDLE=${CURL_CA_BUNDLE} vagrant up --provision
+update-box:
+	@SSL_CERT_FILE=${SSL_CERT_FILE} CURL_CA_BUNDLE=${CURL_CA_BUNDLE} vagrant box update || (echo '\n\nIf you get an SSL error you might be behind a transparent proxy. \nMore info https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/README.md#if-you-are-behind-a-transparent-proxy\n\n' && exit 2)
+
